// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHuCpytnSHHylzTU7dSNP0nmwfGGLFvc4',
    appId: '1:874990207727:web:4a45e8385c198edb6a911a',
    messagingSenderId: '874990207727',
    projectId: 'curious-athlete-417715',
    authDomain: 'curious-athlete-417715.firebaseapp.com',
    storageBucket: 'curious-athlete-417715.appspot.com',
    measurementId: 'G-4EPD2428W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmwDwk0mLLp0nzXYcpWO2d8amj1ju5Uog',
    appId: '1:874990207727:android:296435e745dca5076a911a',
    messagingSenderId: '874990207727',
    projectId: 'curious-athlete-417715',
    storageBucket: 'curious-athlete-417715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1yix0r0qKMUJFyOZWfQPS9sqzSHcB1Y',
    appId: '1:874990207727:ios:4f8eec53f7318f0f6a911a',
    messagingSenderId: '874990207727',
    projectId: 'curious-athlete-417715',
    storageBucket: 'curious-athlete-417715.appspot.com',
    iosBundleId: 'com.example.pranermart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI1yix0r0qKMUJFyOZWfQPS9sqzSHcB1Y',
    appId: '1:874990207727:ios:4f8eec53f7318f0f6a911a',
    messagingSenderId: '874990207727',
    projectId: 'curious-athlete-417715',
    storageBucket: 'curious-athlete-417715.appspot.com',
    iosBundleId: 'com.example.pranermart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHuCpytnSHHylzTU7dSNP0nmwfGGLFvc4',
    appId: '1:874990207727:web:4c031b6f13a1c7e96a911a',
    messagingSenderId: '874990207727',
    projectId: 'curious-athlete-417715',
    authDomain: 'curious-athlete-417715.firebaseapp.com',
    storageBucket: 'curious-athlete-417715.appspot.com',
    measurementId: 'G-T96YBL0ZG5',
  );
}
