final List<String> categories = [
  'Electronics',
  'Fashion',
  'Home & Kitchen',
  'Health & Beauty',
  'Sports & Outdoors',
  'Toys & Games',
  'Books & Stationery',
  'Automotive',
  'Groceries',
  'Furniture & Home Improvement',
  'Office Supplies',
  'Travel & Luggage',
  'Luxury & High-End',
];
final categoriesImage = [
  'assets/category/electronics.png',
  'assets/category/wardrobe.png',
  'assets/category/kitchen.png',
  'assets/category/beauty.png',
  'assets/category/sports.png',
  'assets/category/toy.png',
  'assets/category/books.png',
  'assets/category/car.png',
  'assets/category/basket.png',
  'assets/category/sofa.png',
  'assets/category/organize.png',
  'assets/category/travel.png',
  'assets/category/shopping.png',
];
